apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:8.11.1
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"