apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: dockerhub
  containers:
    - name: node
      image: node:8.11.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
    - name: docker
      image: docker:18.06.1-ce-dind
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-conf
          mountPath: /root/.dockercfg
          subPath: .dockercfg
    - name: skipper
      image: vividseats/skipper:master
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  volumes:
    - name: docker-conf
      configMap:
        name: docker-cfg
